name: Build PMM docs ready for publishing

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install MkDocs and dependencies
        uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
          upgrade: true

      # Build
      - name: Build
        run: mike deploy 2.x -b publish -p
