name: Build PMM docs ready for publishing

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Docker
        run: sudo apt install docker

      - name: Run Docker image
        run: docker --version
