on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    name: MkDocs
    steps:
    - uses: Percona-Lab/percona-doc-docker/mkdocs@v1
    - run: mike --version
