name: MkDocs

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  mkdocs:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Setup MkDocs
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        mike --version
        mkdocs --version
    - name: Setup PlantUML
      run: |
        sudo apt-get install -y plantuml
        plantuml -version
    - name: Run MkDocs
      run: |
        mike deploy 2.x -b publish -p
