name: MkDocs

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  mkdocs:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Setup MkDocs
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup PlantUML
      run: |
        sudo apt install -y graphviz
        sudo mkdir -p /opt/plantuml && wget -O /opt/plantuml/plantuml.jar https://downloads.sourceforge.net/project/plantuml/plantuml.jar
        sudo cp $GITHUB_WORKSPACE/bin/plantuml /usr/local/bin
        sudo chmod +x /usr/local/bin/plantuml
    - name: GitHub credentials
      uses: oleksiyrudenko/gha-git-credentials@v2-latest
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
    - name: Run MkDocs
      run: mike deploy 2.x -b publish -p
