name: Build PMM docs ready for publishing

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: addnab/docker-run-action@v1
        with:
          image: perconalab/pmm-doc-md:latest
          options: --rm -v $GITHUB_WORKSPACE:/docs
          run: mike --version
