name: BUILD PMM DOCS 2.x

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Setup MkDocs
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Setup PlantUML
      run: |
        sudo apt install -y graphviz
        sudo mkdir -p /opt/plantuml && wget -O /opt/plantuml/plantuml.jar https://downloads.sourceforge.net/project/plantuml/plantuml.jar
        sudo cp $GITHUB_WORKSPACE/bin/plantuml /usr/local/bin
        sudo chmod +x /usr/local/bin/plantuml

    - name: Run MkDocs (2.x)
      if: github.ref == 'refs/heads/main'
      run: mkdocs build -f mkdocs-pdf.yml

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: pdf
